#!/bin/bash

function md() {
    mkdir -p $@
    cd $@
}

# list last modified files in given directory
function lh() {
    find $@ -maxdepth 1 \( ! -iname "." \) -exec stat --format '%Y :%y %n' {} \; | sort -nr | cut -d' ' -f5- | head | xargs -exec ls -lhtd --color=auto
}

function lfh() {
    find $@ -maxdepth 1 -type f \( ! -iname "." \) -exec stat --format '%Y :%y %n' {} \; | sort -nr | cut -d' ' -f5- | head | xargs -exec ls -lhtd --color=auto
}

function lt() {
    find $@ -maxdepth 1 \( ! -iname "." \) -exec stat --format '%Y :%y %n' {} \; | sort -nr | cut -d' ' -f5- | tail | xargs -exec ls -lhtd --color=auto
}

# edit the last modified file in the given directory
function lf() {
    find $@ -maxdepth 1 -type f \( ! -iname "." \) -exec stat --format '%Y :%y %n' {} \; | sort -nr | cut -d' ' -f5- | head -n 1
}

# edit the last modified file in the given directory
function el() {
    last=`lf $@`;
    $EDITOR $last
}

function killit() {
ps -eaf | grep $@ | awk '{print $2}' | xargs -exec kill -9
}

function killsudo() {
ps -eaf | grep $@ | awk '{print $2}' | xargs -exec sudo kill -9
}

function sedrepl(){
find . -name "*$1" -type f -exec sed -i 's/'"$2"'/'"$3"'/g' {} \; -print
}

function genpasswd() {
	local l=$1
       	[ "$l" == "" ] && l=16
      	tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${l} | xargs
}

function recordgif() {
    local out=out.gif
    local opts=
    if [ $# \> 0 ]; then opts="-d $1 $opts"; shift; fi
    if [ $# \> 0 ]; then out="$1"; shift; fi
    if [ $# \> 0 ]; then opts="-x $1 $opts"; shift; fi
    if [ $# \> 0 ]; then opts="-y $1 $opts"; shift; fi
    if [ $# \> 0 ]; then opts="-w $1 $opts"; shift; fi
    if [ $# \> 0 ]; then opts="-h $1 $opts"; shift; fi
    byzanz-record $opts $out
}
