#!/usr/bin/env bash
set -e

TEMP=`getopt -o f --long force -n '$0' -- "$@"`
force=false
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

ARGS=
while true; do
    case "$1" in
        -f | --force ) force=true; shift ;;
        -- ) shift; break ;;
        * ) break ;;
    esac
done

here="$(cd "${0%/*}"; pwd)"

for file in "$here"/*; do
    name="$(basename "$file" .md)"
    [[ $name = bin ]] && dotname="$name" || dotname=".${name}"
    dotfull="${HOME}/${dotname}"

    if ! [[ "install readme README" =~ $name || $name =~ ".plist" || -d $file/.git ]]; then
        if [[ ! -e $dotfull || $force = true ]]; then
            ln -sfnv ${file#$HOME/} "$dotfull"
        fi
  fi
done

while read file; do
  bin="bin/${file##*/}"
  fullbin="${here}/${bin}"

  if ! [[ -e "${here}/${file}" ]]; then
    echo "not found: ${file}" >&2
  elif ! [[ -e $fullbin ]]; then
    ln -sfnv "../${file}" "$fullbin"
    echo "$bin" >> "${here}/.git/info/exclude"
  fi
done < "${here}/.external"
